"""
This module contains common functions to draw the causal bayesian networks generated by the
causal_bayesian_networks.py module.
"""

import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

def draw_dag(adjacency_matrix):
    """
    Draw a graph from an adjacency matrix.
    """
    # create a directed graph
    G = nx.from_numpy_array(adjacency_matrix, create_using=nx.DiGraph)
    # draw the graph
    pos = nx.circular_layout(G)
    nx.draw(G, with_labels=True, node_color='lightblue', pos=pos)
    plt.show()

def draw_dag_on_axis(adjacency_matrix, ax):
    """
    Draw a graph from an adjacency matrix on a given axis.
    """
    # create a directed graph
    G = nx.from_numpy_array(adjacency_matrix, create_using=nx.DiGraph)
    # draw the graph
    pos = nx.circular_layout(G)
    nx.draw(G, with_labels=True, node_color='lightblue', pos=pos, ax=ax)

def print_adjacency_matrix(adjacency_matrix):
    """
    Print the adjacency matrix.
    """
    print(pd.DataFrame(adjacency_matrix))
